services:
  - type: web
    name: socity-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn socity_project.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SETTINGS_MODULE
        value: socity_project.settings_prod
      - key: PORT
        value: 8000
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: new-deploy-testing.onrender.com
      - key: DJANGO_DEBUG
        value: "False"
